version: 2
jobs:
  deploy:
    docker:
      - image: "navikt/deployment-cli:v0.1.6"
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t navikt/syfoproxy:$CIRCLE_SHA1.
      - run:
          name: Release docker image
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

            docker tag navikt/syfoproxy:latest -f "navikt/syfoproxy:$CIRCLE_SHA1"

            docker push navikt/syfoproxy:$CIRCLE_SHA1
            docker push navikt/syfoproxy:latest
      - run: # Username and password is set through $DEPLOYMENT_USERNAME and $DEPLOYMENT_PASSWORD
          name: Create deployment request for development
          command: deployment-cli deploy create --cluster=dev-sbs --repository=navikt/syfoproxy --team=teamsykefravr -r=nais.yaml --version=$CIRCLE_SHA1 --vars=syfotekster/dev-sbs.json
#      - run: # Username and password is set through $DEPLOYMENT_USERNAME and $DEPLOYMENT_PASSWORD
#          name: Create deployment request for prod
#          command: deployment-cli deploy create --cluster=prod-fss --repository=navikt/syfoproxy --team=teamsykefravr -r=nais.yaml --version=${CIRCLE_SHA1}
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
